apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frontend
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./foodbyte-frontend
      sourceRef:
        kind: GitRepository
        name: foodbyte-flux
        namespace: flux-system
  valuesFiles: ["values.yaml"]
