apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "foodbyte-notification-service.fullname" . }}
  labels:
    {{- include "foodbyte-notification-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "foodbyte-notification-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "foodbyte-notification-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-rabbitmq
          image: alpine:3.21
          command:
            - sh
            - -c
            - >
              {{- if .Values.externalDatabase.enabled }}
              echo "External MQ used, skipping wait"
              {{- else }}
              until nc -z {{ .Release.Name }}-rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done;
              {{- end }}
        - name: wait-for-redis
          image: alpine:3.21
          command:
            - sh
            - -c
            - >
              {{- if .Values.externalDatabase.enabled }}
              echo "External Redis used, skipping wait"
              {{- else }}
              until nc -z {{ .Release.Name }}-redis 6379; do echo waiting for redis; sleep 2; done;
              {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8004
              protocol: TCP
          env:
            - name: RABBITMQ_URL
              {{- if .Values.externalDatabase.enabled }}
              value: {{ .Values.externalDatabase.rabbitUrl | quote }}
              {{- else }}
              value: "amqp://{{ .Values.devRabbitMQ.user }}:{{ .Values.devRabbitMQ.password }}@{{ .Release.Name }}-rabbitmq:5672/"
              {{- end }}
            - name: REDIS_URL
              {{- if .Values.externalDatabase.enabled }}
              value: {{ .Values.externalDatabase.redisUrl | quote }}
              {{- else }}
              value: "redis://:{{ .Values.devRedis.password }}@{{ .Release.Name }}-redis:6379/0"
              {{- end }}
          livenessProbe:
            http-get: { path: /api/notifications/health, port: http }
          readinessProbe:
            http-get: { path: /api/notifications/health, port: http }
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
