apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "foodbyte-restaurant-service.fullname" . }}
  labels:
    {{- include "foodbyte-restaurant-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "foodbyte-restaurant-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "foodbyte-restaurant-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-db
          image: alpine:3.21
          command:
            - sh
            - -c
            - >
              {{- if .Values.externalDatabase.enabled }}
              echo "External DB used, skipping wait-for-local-db"
              {{- else }}
              until nc -z {{ .Release.Name }}-db 27017; do echo waiting for mongo; sleep 2; done;
              {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8002
              protocol: TCP
          env:
            - name: MONGODB_URL
              {{- if .Values.externalDatabase.enabled }}
              value: {{ .Values.externalDatabase.url | quote }}
              {{- else }}
              value: "mongodb://{{ .Values.devMongo.user }}:{{ .Values.devMongo.password }}@{{ .Release.Name }}-db:27017/?authSource=admin"
              {{- end }}
            - name: MONGODB_DB
              {{- if .Values.externalDatabase.enabled }}
              value: {{ .Values.externalDatabase.dbName | quote }}
              {{- else }}
              value: {{ .Values.devMongo.database | quote }}
              {{- end }}
            - name: JWT_SECRET
              value: "your_jwt_secret"
          livenessProbe:
            http-get: { path: /api/restaurants/health, port: http }
          readinessProbe:
            http-get: { path: /api/restaurants/health, port: http }
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
