replicaCount: 1

image:
  repository: ghcr.io/ansuman-satapathy/foodbyte-user-service
  pullPolicy: IfNotPresent
  tag: "3b65f1a5f6b9c0a6c9a6b3ce79ace4df945bf4da"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8001

ingress: { enabled: false }
httpRoute: { enabled: false }

useSecrets: false

externalDatabase:
  enabled: false
  url: ""

imagePullSecrets: []

resources: {} 

autoscaling: { enabled: false }
nodeSelector: {}
tolerations: []
affinity: {}

livenessProbe:
  httpGet:
    path: /api/users/health
    port: http
readinessProbe:
  httpGet:
    path: /api/users/health
    port: http

devPostgres:
  enabled: true
  user: user_admin
  password: user_pass
  database: user_db
  persistence:
    enabled: true
    size: 5Gi
    storageClass: ""

appConfig:
  jwtSecret: "your_jwt_secret"
  jwtAlgorithm: "HS256"
  jwtExpireMinutes: 60
