replicaCount: 2

externalDatabase:
  enabled: true
  url: "REPLACE_WITH_RDS_POSTGRES_ENDPOINT"

imagePullSecrets:
  - name: ghcr-pull-secret

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
