replicaCount: 1

image:
  repository: ghcr.io/ansuman-satapathy/foodbyte-order-service
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8003

ingress: { enabled: false }
httpRoute: { enabled: false }
resources: {}
autoscaling: { enabled: false }
nodeSelector: {}
tolerations: []
affinity: {}

livenessProbe:
  httpGet: { path: /health, port: http }
readinessProbe:
  httpGet: { path: /health, port: http }

devPostgres:
  enabled: true
  user: order_user
  password: order_password
  database: order_db

devRabbitMQ:
  enabled: true
  user: user
  password: password

appConfig:
  jwtSecret: "your_jwt_secret"
  jwtAlgorithm: "HS256"
  jwtExpireMinutes: 60
  restaurantServiceUrl: "http://restaurant-service-foodbyte-restaurant-service:8002"
