{{- if .Values.devPostgres.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-db
spec:
  serviceName: {{ .Release.Name }}-db
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.devPostgres.user | quote }}
            - name: POSTGRES_PASSWORD
              {{- if .Values.useSecrets }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "foodbyte-order-service.fullname" . }}-secrets
                  key: postgres-password
              {{- else }}
              value: {{ .Values.devPostgres.password | quote }}
              {{- end }}
            - name: POSTGRES_DB
              value: {{ .Values.devPostgres.database | quote }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.devPostgres.persistence.storageClass }}
        storageClassName: {{ .Values.devPostgres.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.devPostgres.persistence.size | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
spec:
  selector:
    app: {{ .Release.Name }}-db
  ports:
    - port: 5432
      targetPort: 5432
{{- end }}
