{{- if .Values.devRabbitMQ.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-rabbitmq
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:4.0-management-alpine
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: {{ .Values.devRabbitMQ.user | quote }}
            - name: RABBITMQ_DEFAULT_PASS
              value: {{ .Values.devRabbitMQ.password | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rabbitmq
spec:
  selector:
    app: {{ .Release.Name }}-rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: http
      port: 15672
      targetPort: 15672
{{- end }}
