apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "foodbyte-order-service.fullname" . }}
  labels:
    {{- include "foodbyte-order-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "foodbyte-order-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "foodbyte-order-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-db
          image: alpine:3.21
          command:
            - sh
            - -c
            - >
              {{- if .Values.externalDatabase.enabled }}
              echo "External DB used, skipping wait-for-local-db"
              {{- else }}
              until nc -z {{ .Release.Name }}-db 5432; do echo waiting for postgres; sleep 2; done;
              {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8003
              protocol: TCP
          env:
            - name: DATABASE_URL
              {{- if .Values.externalDatabase.enabled }}
              value: {{ .Values.externalDatabase.url | quote }}
              {{- else }}
              value: "postgresql://{{ .Values.devPostgres.user }}:{{ .Values.devPostgres.password }}@{{ .Release.Name }}-db:5432/{{ .Values.devPostgres.database }}"
              {{- end }}
            - name: JWT_SECRET
              value: "your_jwt_secret"
            - name: RABBITMQ_URL
              value: "amqp://{{ .Values.devRabbitMQ.user }}:{{ .Values.devRabbitMQ.password }}@{{ .Release.Name }}-rabbitmq:5672/"
          livenessProbe:
            http-get: { path: /api/orders/health, port: http }
          readinessProbe:
            http-get: { path: /api/orders/health, port: http }
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
