replicaCount: 1

image:
  repository: ghcr.io/ansuman-satapathy/foodbyte-notification-service
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8004

ingress: { enabled: false }
httpRoute: { enabled: false }
resources: {}
autoscaling: { enabled: false }
nodeSelector: {}
tolerations: []
affinity: {}

livenessProbe:
  httpGet:
    path: /api/notifications/health
    port: http
readinessProbe:
  httpGet:
    path: /api/notifications/health
    port: http

devRabbitMQ:
  enabled: true
  user: user
  password: password

devRedis:
  enabled: true
  password: password

appConfig:
  dedupTtlSeconds: 3600
