replicaCount: 2

externalDatabase:
  enabled: true
  redisUrl: "REPLACE_WITH_ELASTICACHE_ENDPOINT"
  rabbitUrl: "REPLACE_WITH_AMAZON_MQ_ENDPOINT"

imagePullSecrets:
  - name: ghcr-pull-secret

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
