replicaCount: 1

image:
  repository: ghcr.io/ansuman-satapathy/foodbyte-notification-service
  pullPolicy: IfNotPresent
  tag: "7ed02c635a6ebeb156a675a267d48ba3aff8a0b5"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8004

ingress: { enabled: false }
httpRoute: { enabled: false }

useSecrets: false

externalDatabase:
  enabled: false
  redisUrl: ""
  rabbitUrl: ""

imagePullSecrets: []

resources: {} 

autoscaling: { enabled: false }
nodeSelector: {}
tolerations: []
affinity: {}

livenessProbe:
  httpGet:
    path: /api/notifications/health
    port: http
readinessProbe:
  httpGet:
    path: /api/notifications/health
    port: http

devRabbitMQ:
  enabled: true
  user: user
  password: password
  persistence:
    enabled: true
    size: 5Gi
    storageClass: ""

devRedis:
  enabled: true
  password: password
  persistence:
    enabled: true
    size: 2Gi
    storageClass: ""

appConfig:
  dedupTtlSeconds: 3600
